services:
  mysql:
    restart: always
    image: mysql:8.3.0
    container_name: mysql
    expose:
      - '3306'
    networks:
      - mysql_network
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
    ports:
      - '3306:3306'
    volumes:
      - ./mysql:/var/lib/mysql

  status-backend:
    restart: always
    container_name: status-backend
    build: .
    command: sh -c "rm -rf node_modules && npm install && npm run dev"
    ports:
      - '3001:3001'
    networks:
      - mysql_network
    depends_on:
      - mysql
    image: status-backend
  
  dragonfly:
    restart: unless-stopped
    image: ghcr.io/dragonflydb/dragonfly:latest
    container_name: dragonfly
    ports:
      - '6379:6379'
    networks:
      - mysql_network
    volumes:
      - dragonfly-data:/data/dragonfly

volumes:
  dragonfly-data:

networks:
  mysql_network:
    driver: bridge
