import { sequelize } from '../db/database.js';

/**
   * Generates the SQL query string that Sequelize would use for a specific query.
   * WARNING: This is a hacky way to capture the SQL string generated by Sequelize, but it
   * not might be a 1:1 match with the actual SQL executed on the database (I've found a source
   * stating this that I can't find right now). Use with caution and track if in the future
   * such feature is added to Sequelize.
   * TODO: Investigate as well the move to another ORM like Prisma, that could better allow this.
   *
   * @param {import('sequelize').ModelStatic<import('sequelize').Model>} model - The sequelize model against which the query is executed.
   * @param {keyof import('sequelize').ModelStatic<import('sequelize').Model>} action - The action to be performed (findAll, findOne, etc.).
   * @param {import('sequelize').FindOptions} options - Options for the query
   * @returns {Promise<string | undefined>} - The SQL string generated by Sequelize.
   */
export async function getSQLFromSequelize(model, action, ...params) {
  let sqlString;
  const t = await sequelize.transaction();

  const callParams = [];
  const options = {
    logging: (sql) => {
      const match = sql.match(/:\s*(SELECT[\s\S]*?)$/i);
      if (match) {
        sqlString = match[1].trim();
      } else {
        sqlString = sql.trim();
      }
    },
    transaction: t
  };

  for (const param of params) {
    if (typeof param === 'object' && param !== null) {
      Object.assign(options, param);
    } else {
      callParams.push(param);
    }
  }

  callParams.push(options);
  await model[action](...callParams);
  await t.rollback();

  return sqlString;
}

export function parseSQLQuery(query) {
  const result = {
    aggregations: [],
    columns: [],
    whereConditions: [],
    whereLogic: 'AND',
    groupBy: null,
    orderByAttr: null,
    orderDirection: null,
    table: null,
    alias: null,
  };

  // Table name and alias
  const tableMatch = query.match(/FROM\s+["']?(\w+)["']?(?:\s+AS\s+["']?(\w+)["']?)?/i);
  if (tableMatch) {
    result.table = tableMatch[1];
    result.alias = tableMatch[2] || null;
  }

  // Columns and Aggregations
  const selectMatch = query.match(/SELECT\s+(.+?)\s+FROM/i);
  if (selectMatch) {
    const selectPart = selectMatch[1].trim();
    
    // Si es un SELECT *
    if (selectPart === '*') {
      result.columns = ['*'];
    } else {
      const selectFields = selectPart.split(',').map(f => f.trim());
      selectFields.forEach((field) => {
        const aggMatch = field.match(/^(\w+)\((\*|[^()]*?)\)$/);
        if (aggMatch) {
          result.aggregations.push({
            func: aggMatch[1],
            attr: aggMatch[2],
          });
        } else if (field !== '*') {
          result.columns.push(field);
        } else {
          result.columns.push('*');
        }
      });
    }
  }
  // WHERE conditions
  const whereMatch = query.match(/WHERE\s+\((.+?)\)(?:\s+|$)/i);
  if (whereMatch) {
    const whereClause = whereMatch[1];
    
    // Determine if we're using AND or OR logic
    if (whereClause.includes(' AND ')) {
      result.whereLogic = 'AND';
      parseConditions(whereClause.split(' AND '), result);
    } else if (whereClause.includes(' OR ')) {
      result.whereLogic = 'OR';
      parseConditions(whereClause.split(' OR '), result);
    } else {
      // Single condition
      parseSingleCondition(whereClause, result);
    }
  }

  // GROUP BY
  const groupByMatch = query.match(/GROUP\s+BY\s+(\w+)/i);
  if (groupByMatch) {
    result.groupBy = groupByMatch[1];
  }

  // ORDER BY
  const orderByMatch = query.match(/ORDER\s+BY\s+(\w+)(?:\s+(ASC|DESC))?/i);
  if (orderByMatch) {
    result.orderByAttr = orderByMatch[1];
    result.orderDirection = orderByMatch[2]
      ? orderByMatch[2].toUpperCase()
      : 'ASC';
  }

  // LIMIT and OFFSET
  const limitMatch = query.match(/LIMIT\s+(\d+)/i);
  if (limitMatch) {
    result.limit = parseInt(limitMatch[1], 10);
  }

  const offsetMatch = query.match(/OFFSET\s+(\d+)/i);
  if (offsetMatch) {
    result.offset = parseInt(offsetMatch[1], 10);
  }

  return result;
}

function parseConditions(conditions, result) {
  conditions.forEach((condition) => {
    parseSingleCondition(condition.trim(), result);
  });
}

function parseSingleCondition(condition, result) {
  // Support for different operators (=, >, <, >=, <=, !=, LIKE)
  const operatorPattern = /\s*(>=|<=|!=|LIKE|=|>|<)\s*/i;
  const parts = condition.split(operatorPattern);
  
  if (parts.length >= 3) {
    const key = parts[0].trim();
    const operator = parts[1].trim();
    const rawValue = parts[2].trim();
    
    result.whereConditions.push({
      key: key,
      operator: operator,
      value: parseWhereValue(rawValue),
    });
  }
}

function parseWhereValue(value) {
  // Remove surrounding single or double quotes
  const cleanValue = value.replace(/(^['"])|(['"]$)/g, '');
  
  // Convert booleans
  if (cleanValue.toLowerCase() === 'true') {
    return true;
  }
  if (cleanValue.toLowerCase() === 'false') {
    return false;
  }
  
  // Always convert numeric values to a float
  if (!isNaN(cleanValue) && cleanValue !== '') {
    return parseFloat(cleanValue);
  }
  
  return cleanValue;
}
