import { sequelize } from '../db/database.js';

/**
   * Generates the SQL query string that Sequelize would use for a specific query.
   * WARNING: This is a hacky way to capture the SQL string generated by Sequelize, but it
   * not might be a 1:1 match with the actual SQL executed on the database (I've found a source
   * stating this that I can't find right now). Use with caution and track if in the future
   * such feature is added to Sequelize.
   * TODO: Investigate as well the move to another ORM like Prisma, that could better allow this.
   *
   * @param {import('sequelize').ModelStatic<import('sequelize').Model>} model - The sequelize model against which the query is executed.
   * @param {keyof import('sequelize').ModelStatic<import('sequelize').Model>} action - The action to be performed (findAll, findOne, etc.).
   * @param {import('sequelize').FindOptions} options - Options for the query
   * @returns {Promise<string | undefined>} - The SQL string generated by Sequelize.
   */
export async function getSQLFromSequelize(model, action, ...params) {
  let sqlString;
  const t = await sequelize.transaction();
  const parsed_params = []
  const obj_params = {
    logging: (sql) => {
      const [,sql_query] = sql.split(':')
      if (sql_query) {
        sqlString = sql_query.trim();
      }
    },
    transaction: t
  }

  for (const param of params) {
    if (Array.isArray(param)) {
      parsed_params.push(param)
    } else if (typeof param === 'object' && param !== null) {
      Object.assign(obj_params, param);
    }
  }

  await model[action](...[...parsed_params, obj_params]);
  await t.rollback();

  return sqlString;
}

/**
 * Genera una consulta SQL dinámica basada en los parámetros proporcionados.
 *
 * @param {Object} sql - Objeto con los parámetros para construir la consulta.
 * @param {Array<{func: string, attr: string}>} [sql.aggregations=[]] - Lista de agregaciones, cada una con su función (COUNT, AVG, etc.) y el atributo correspondiente.
 * @param {Array<string>} [sql.columns=[]] - Lista de columnas a seleccionar en la consulta.
 * @param {Array<{key: string, operator: string, value: any}>} [sql.whereConditions=[]] - Lista de condiciones para la cláusula WHERE, cada una con una clave, un operador y un valor.
 * @param {string} [sql.whereLogic='AND'] - Operador lógico que une las condiciones WHERE ('AND' o 'OR').
 * @param {string} [sql.groupBy] - Columna por la que se agruparán los resultados.
 * @param {string} [sql.orderByAttr] - Columna por la que se ordenarán los resultados.
 * @param {string} [sql.orderDirection='ASC'] - Dirección de orden (ASC o DESC).
 * @param {string} [sql.table='computation'] - Nombre de la tabla, por defecto 'computation'.
 *
 * @returns {string} - La consulta SQL generada.
 */

function createSQLQuery({
  aggregations = [],
  columns = [],
  whereConditions = [],
  whereLogic = 'AND',
  groupBy,
  orderByAttr,
  orderDirection,
  table = 'computation',
}) {
  let query = 'SELECT ';

  // Aggregations
  if (aggregations.length > 0) {
    query += aggregations
      .map((agg) => `${agg.func}(${agg.attr})`)
      .join(', ');
  }

  // Raw columns
  if (columns.length > 0) {
    if (aggregations.length > 0) query += ', ';
    query += columns.map((col) => `${col}`).join(', ');
  }

  if (aggregations.length === 0 && columns.length === 0) {
    query += '*';
  }

  query += ` FROM statusdb.${table}`;

  // WHERE
  if (whereConditions.length > 0) {
    const whereClause = whereConditions
      .map((cond) => {
        const value =
                    typeof cond.value === 'number' ||
                    cond.value === true ||
                    cond.value === false
                      ? cond.value
                      : `'${cond.value}'`;
        return `${cond.key} ${cond.operator} ${value}`;
      })
      .join(` ${whereLogic} `);
    query += ` WHERE (${whereClause})`;
  }

  // GROUP BY
  if (groupBy) {
    query += ` GROUP BY ${groupBy}`;
  }

  // ORDER BY
  if (orderByAttr) {
    const direction =
            orderDirection && orderDirection.toUpperCase() === 'DESC'
              ? 'DESC'
              : 'ASC';
    query += ` ORDER BY ${orderByAttr} ${direction}`;
  }

  return query;
}

function parseSQLQuery(query) {
  const result = {
    aggregations: [],
    columns: [],
    whereConditions: [],
    whereLogic: 'AND',
    groupBy: null,
    orderByAttr: null,
    orderDirection: null,
    table: 'computation',
  };

  // Table
  const tableMatch = query.match(/FROM\s+statusdb\.(\w+)/i);
  if (tableMatch) {
    result.table = tableMatch[1];
  }

  // Columns and Aggregations
  const selectMatch = query.match(/SELECT\s+(.+?)\s+FROM/i);
  if (selectMatch) {
    const selectFields = selectMatch[1].split(',');
    selectFields.forEach((field) => {
      field = field.trim();
      const aggMatch = field.match(/(\w+)\((\*)\)/); // ej: COUNT(*)
      if (aggMatch) {
        result.aggregations.push({
          func: aggMatch[1],
          attr: aggMatch[2],
        });
      } else {
        result.columns.push(field);
      }
    });
  }

  // WHERE
  const whereMatch = query.match(/WHERE\s+\((.+)\)/i);
  if (whereMatch) {
    const conditions = whereMatch[1].split(/\s+(AND|OR)\s+/i);
    if (conditions.length === 1) {
      const [key, operator, value] = conditions[0].split(
        /\s+(=|>|<|>=|<=|!=)\s+/
      );
      result.whereConditions.push({
        key: key.trim(),
        operator: operator.trim(),
        value: parseWhereValue(value.trim()),
      });
    } else {
      result.whereLogic = conditions[1].toUpperCase() || 'AND'; // AND or OR
      conditions.forEach((condition) => {
        if (condition !== 'AND' && condition !== 'OR') {
          const [key, operator, value] = condition.split(
            /\s+(=|>|<|>=|<=|!=)\s+/
          );
          result.whereConditions.push({
            key: key.trim(),
            operator: operator.trim(),
            value: parseWhereValue(value.trim()),
          });
        }
      });
    }
  }

  // GROUP BY
  const groupByMatch = query.match(/GROUP\s+BY\s+(\w+)/i);
  if (groupByMatch) {
    result.groupBy = groupByMatch[1];
  }

  // ORDER BY
  const orderByMatch = query.match(/ORDER\s+BY\s+(\w+)\s+(ASC|DESC)?/i);
  if (orderByMatch) {
    result.orderByAttr = orderByMatch[1];
    result.orderDirection = orderByMatch[2]
      ? orderByMatch[2].toUpperCase()
      : 'ASC';
  }

  return result;
}

function parseWhereValue(value) {
  if (value.toLowerCase() === 'true') {
    return true;
  }
  if (value.toLowerCase() === 'false') {
    return false;
  }
  if (!isNaN(value)) {
    return value;
  }
  return value.replace(/['"]/g, '');
}

export { createSQLQuery, parseSQLQuery };

/* EJEMPLOS
SELECT * FROM statusdb.computation
{}

SELECT id, date FROM statusdb.computation WHERE (id > '5' AND limit < '5')
{
    "columns": ["id", "date"],
    "whereConditions": [
        { "key": "id", "operator": ">", "value": 5 },
        { "key": "limit", "operator": "<", "value": 5 }
    ],
    "whereLogic": "AND"
}

SELECT COUNT(limit), MAX(date) FROM statusdb.computation
{
    "aggregations": [
        { "func": "COUNT", "attr": "limit" },
        { "func": "MAX", "attr": "date" }
    ]
}

SELECT COUNT(limit) FROM statusdb.computation WHERE (available != '5' OR active = '1') GROUP BY limit
{
    "aggregations": [
        { "func": "COUNT", "attr": "limit" }
    ],
    "whereConditions": [
        { "key": "available", "operator": "!=", "value": "5" },
        { "key": "active", "operator": "=", "value": "1" }
    ],
    "whereLogic": "OR",
    "groupBy": "limit"
}

SELECT id FROM statusdb.computation ORDER BY limit ASC
{
    "columns": ["id"],
    "orderByAttr": "limit",
    "orderDirection": "ASC"
}

SELECT COUNT(limit), id FROM statusdb.computation WHERE (id > '5' AND limit <= '10')
{
    "columns": ["id"],
    "aggregations": [
        { "func": "COUNT", "attr": "limit" }
    ],
    "whereConditions": [
        { "key": "id", "operator": ">", "value": 5 },
        { "key": "limit", "operator": "<=", "value": 10 }
    ],
    "whereLogic": "AND"
}
*/
