import { sequelize } from '../db/database.js';

/**
   * Generates the SQL query string that Sequelize would use for a specific query.
   * WARNING: This is a hacky way to capture the SQL string generated by Sequelize, but it
   * not might be a 1:1 match with the actual SQL executed on the database (I've found a source
   * stating this that I can't find right now). Use with caution and track if in the future
   * such feature is added to Sequelize.
   * TODO: Investigate as well the move to another ORM like Prisma, that could better allow this.
   *
   * @param {import('sequelize').ModelStatic<import('sequelize').Model>} model - The sequelize model against which the query is executed.
   * @param {keyof import('sequelize').ModelStatic<import('sequelize').Model>} action - The action to be performed (findAll, findOne, etc.).
   * @param {import('sequelize').FindOptions} options - Options for the query
   * @returns {Promise<string | undefined>} - The SQL string generated by Sequelize.
   */
export async function getSQLFromSequelize(model, action, ...params) {
  let sqlString;
  const t = await sequelize.transaction();

  const callParams = [];
  const options = {
    logging: (sql) => {
      const [, query] = sql.split(':');
      if (query) sqlString = query.trim();
    },
    transaction: t
  };

  for (const param of params) {
    if (Array.isArray(param)) {
      callParams.push(param);
    } else if (typeof param === 'object' && param !== null) {
      Object.assign(options, param);
    }
  }

  callParams.push(options);
  await model[action](...callParams);
  await t.rollback();

  return sqlString;
}

export function parseSQLQuery(query) {
  const result = {
    aggregations: [],
    columns: [],
    whereConditions: [],
    whereLogic: 'AND',
    groupBy: null,
    orderByAttr: null,
    orderDirection: null,
    tableName: null,
    alias: null,
  };

  // Table name and alias
  const tableMatch = query.match(/FROM\s+"([^"]+)"(?:\s+AS\s+"([^"]+)")?/i);
  if (tableMatch) {
    result.tableName = tableMatch[1];
    if (tableMatch[2]) {
      result.alias = tableMatch[2];
    }
  }

  // Columns and Aggregations
  const selectMatch = query.match(/SELECT\s+(.+?)\s+FROM/i);
  if (selectMatch) {
    const selectFields = selectMatch[1].split(',');
    selectFields.forEach((field) => {
      field = field.trim();
      const aggMatch = field.match(/(\w+)\((\*|[^)]+)\)/);
      if (aggMatch) {
        result.aggregations.push({
          func: aggMatch[1],
          attr: aggMatch[2],
        });
      } else {
        result.columns.push(field);
      }
    });
  }

  // WHERE
  const whereMatch = query.match(/WHERE\s+\((.+)\)/i);
  if (whereMatch) {
    const conditions = whereMatch[1].split(/\s+(AND|OR)\s+/i);
    if (conditions.length === 1) {
      const [key, operator, value] = conditions[0].split(/\s+(=|>|<|>=|<=|!=)\s+/);
      result.whereConditions.push({
        key: key.trim(),
        operator: operator.trim(),
        value: parseWhereValue(value.trim()),
      });
    } else {
      result.whereLogic = conditions[1].toUpperCase() || 'AND'; // AND or OR
      conditions.forEach((condition) => {
        if (condition !== 'AND' && condition !== 'OR') {
          const [key, operator, value] = condition.split(/\s+(=|>|<|>=|<=|!=)\s+/);
          result.whereConditions.push({
            key: key.trim(),
            operator: operator.trim(),
            value: parseWhereValue(value.trim()),
          });
        }
      });
    }
  }

  // GROUP BY
  const groupByMatch = query.match(/GROUP\s+BY\s+(\w+)/i);
  if (groupByMatch) {
    result.groupBy = groupByMatch[1];
  }

  // ORDER BY
  const orderByMatch = query.match(/ORDER\s+BY\s+(\w+)\s+(ASC|DESC)?/i);
  if (orderByMatch) {
    result.orderByAttr = orderByMatch[1];
    result.orderDirection = orderByMatch[2]
      ? orderByMatch[2].toUpperCase()
      : 'ASC';
  }

  return result;
}

function parseWhereValue(value) {
  if (value.toLowerCase() === 'true') {
    return true;
  }
  if (value.toLowerCase() === 'false') {
    return false;
  }
  if (!isNaN(value)) {
    return value;
  }
  return value.replace(/['"]/g, '');
}
