import { DataTypes } from "sequelize";
import sequelize from "../../db/database.js";

const Dashboard = sequelize.define(
    "Dashboard",
    {
        id: {
            type: DataTypes.UUID,
            defaultValue: DataTypes.UUIDV4,
            primaryKey: true,
        },
        results: {
            type: DataTypes.JSON,
            allowNull: false,
        },
        start_date: {
            type: DataTypes.DATE,
            allowNull: false,
        },
        end_date: {
            type: DataTypes.DATE,
            allowNull: false,
        },
    },
    {
        tableName: "dashboard",
        timestamps: false,
    }
);

export default Dashboard;

/**
 * @swagger
 * components:
 *   schemas:
 *     Dashboard:
 *       type: object
 *       properties:
 *         id:
 *           type: string
 *           format: uuid
 *           description: The autogenerated id of the dashboard
 *         control_id:
 *           type: string
 *           description: The ID of the related control
 *         results:
 *           type: array
 *           items:
 *             type: object
 *           description: JSON array containing the results from another server
 *         start_date:
 *           type: string
 *           format: date-time
 *           description: The start date of the dashboard data
 *         end_date:
 *           type: string
 *           format: date-time
 *           description: The end date of the dashboard data
 *       required:
 *         - control_id
 *         - results
 *         - start_date
 *         - end_date
 *       example:
 *         id: d290f1ee-6c54-4b01-90e6-d701748f0851
 *         control_id: 1
 *         results: [
 *           { "index": "190293", "result": true },
 *           { "index": "190294", "result": true }
 *         ]
 *         start_date: 2023-01-01T00:00:00.000Z
 *         end_date: 2023-01-31T23:59:59.000Z
 */
