name: Build and Push Docker Image

on:
  push:
    branches:
      - main
      - develop
    tags:
      - "*.*.*"
  pull_request:
    branches:
      - main
      - develop
    types:
      - labeled

env:
  REGISTRY_IMAGE: ${{ secrets.DOCKER_USERNAME }}/status-backend
  GHCR_IMAGE: statuscompliance/status-backend
  PR_ID: ${{ github.event.pull_request.number }}
  TAG: ${{ github.ref_name }}
  COMMIT_SHA: ${{ github.sha }}

jobs:
  build:
    runs-on: ubuntu-latest
    if: (github.event.pull_request && github.event.label.name == '🐳 Dockerize')  || github.event_name == 'push'

    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    
    steps:
      - name: Checkout ⬇️
        uses: actions/checkout@v4.2.2
        with:
          show-progress: false

      - name: Configure QEMU ⚙️
        uses: docker/setup-qemu-action@v3.3.0

      - name: Configure Docker Buildx ⚙️
        uses: docker/setup-buildx-action@v3.8.0

      - name: Login to DockerHub 🔑
        uses: docker/login-action@v3.3.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Login to GitHub Container Registry 🔑
        uses: docker/login-action@v3.3.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6.13.0
        with:
          context: .
          file: Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: |
            ${{ startsWith(github.ref, 'refs/tags/') && format('{0}:{1}', env.REGISTRY_IMAGE, env.TAG) || '' }}
            ${{ github.ref == 'refs/heads/main' && format('{0}:latest', env.REGISTRY_IMAGE) || '' }}
            ${{ github.ref == 'refs/heads/develop' && github.event_name == 'push' && format('{0}:unstable-{1}', env.REGISTRY_IMAGE, env.COMMIT_SHA ) || '' }}
            ${{ github.event_name == 'pull_request' && format('{0}:PR.{1}', env.REGISTRY_IMAGE, env.PR_ID) || '' }}

      - name: Build and Push Ghcr Image
        uses: docker/build-push-action@v6.13.0
        with:
          context: .
          file: Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: |
            ${{ startsWith(github.ref, 'refs/tags/') && format('ghcr.io/{0}:{1}', env.GHCR_IMAGE, env.TAG) || '' }}
            ${{ github.ref == 'refs/heads/main' && format('ghcr.io/{0}:latest', env.GHCR_IMAGE) || '' }}
            ${{ github.ref == 'refs/heads/develop' && github.event_name == 'push' && format('ghcr.io/{0}:unstable-{1}', env.GHCR_IMAGE, env.COMMIT_SHA ) || '' }}
            ${{ github.event_name == 'pull_request' && format('ghcr.io/{0}:PR.{1}', env.GHCR_IMAGE, env.PR_ID) || '' }}