name: Build and Push Docker Image

on:
    push:
        branches:
            - develop
            - main
        tags:
            - "*.*.*"
    pull_request:
        branches:
            - develop
            - main
        types:
            - labeled

env:
    REGISTRY_IMAGE: ${{ secrets.DOCKER_USERNAME }}/status-backend
    PR_ID: ${{ github.event.pull_request.number }}
    TAG: ${{ github.ref_name }}

jobs:
    build:
        runs-on: ubuntu-latest
        if: (github.event.pull_request && github.event.label.name == 'dockerize')  || github.event_name == 'push'

        steps:
            - name: Checkout ⬇️
              uses: actions/checkout@v4.2.2
              with:
                  show-progress: false

            - name: Configure QEMU ⚙️
              uses: docker/setup-qemu-action@v3.2.0

            - name: Configure Docker Buildx ⚙️
              uses: docker/setup-buildx-action@v3.7.1

            - name: Login to DockerHub 🔑
              uses: docker/login-action@v3.3.0
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}                     

            - name: Build and Push Docker Image
              uses: docker/build-push-action@v6.10.0
              with:
                  context: .
                  file: Dockerfile
                  platforms: linux/amd64,linux/arm64
                  push: true
                  cache-from: type=gha
                  cache-to: type=gha,mode=max
                  tags: |
                      ${{ startsWith(github.ref, 'refs/tags/') && format('{0}:{1}', env.REGISTRY_IMAGE, env.TAG) || '' }}
                      ${{ github.ref == 'refs/heads/main' && format('{0}:latest', env.REGISTRY_IMAGE) || '' }}
                      ${{ github.ref == 'refs/heads/develop' && format('{0}:develop', env.REGISTRY_IMAGE) || '' }}
                      ${{ github.event_name == 'pull_request' && format('{0}:PR.{1}', env.REGISTRY_IMAGE, env.PR_ID) || '' }}