import { vi } from 'vitest';

export const mockGrafana = {
  serviceAccount: {
    createServiceAccount: vi.fn(),
    createToken: vi.fn(),
    deleteServiceAccount: vi.fn(),
    deleteToken: vi.fn(),
    listTokens: vi.fn(),
    retrieveServiceAccount: vi.fn(),
    searchOrgServiceAccountsWithPaging: vi.fn(),
    updateServiceAccount: vi.fn(),
  },
  folder: {
    createFolder: vi.fn(),
    deleteFolder: vi.fn(),
    getFolderByID: vi.fn(),
    getFolderByUID: vi.fn(),
    getFolderDescendantCounts: vi.fn(),
    getFolders: vi.fn(),
    moveFolder: vi.fn(),
    updateFolder: vi.fn(),
  },
  datasource: {
    addDataSource: vi.fn(),
    callDatasourceResourceByID: vi.fn(),
    callDatasourceResourceWithUID: vi.fn(),
    checkDatasourceHealthByID: vi.fn(),
    checkDatasourceHealthWithUID: vi.fn(),
    datasourceProxyDELETEByUIDcalls: vi.fn(),
    datasourceProxyDELETEcalls: vi.fn(),
    datasourceProxyGETByUIDcalls: vi.fn(),
    datasourceProxyGETcalls: vi.fn(),
    datasourceProxyPOSTByUIDcalls: vi.fn(),
    datasourceProxyPOSTcalls: vi.fn(),
    deleteDataSourceByID: vi.fn(),
    deleteDataSourceByName: vi.fn(),
    deleteDataSourceByUID: vi.fn(),
    getDataSourceByID: vi.fn(),
    getDataSourceByName: vi.fn(),
    getDataSourceByUID: vi.fn(),
    getDataSourceIdByName: vi.fn(),
    getDataSources: vi.fn(),
    updateDataSourceByID: vi.fn(),
    updateDataSourceByUID: vi.fn(),
  },
  dashboard: {
    calculateDashboardDiff: vi.fn(),
    deleteDashboardByUID: vi.fn(),
    getDashboardByUID: vi.fn(),
    getDashboardTags: vi.fn(),
    getHomeDashboard: vi.fn(),
    hardDeleteDashboardByUID: vi.fn(),
    importDashboard: vi.fn(),
    postDashboard: vi.fn(),
    restoreDeletedDashboardByUID: vi.fn(),
  },
  search: {
    listSortOptions: vi.fn(),
    search: vi.fn(),
  },
};
